replace broken image
build 2019.4.0.383.0-zpm seems to exit with **SHELL ["/irissession.sh"]**
this breaks further processing:
~~~
ERROR: Service 'iris' failed to build : The command 
'/irissession.sh chown ${ISC_PACKAGE_MGRUSER}:${ISC_PACKAGE_IRISGROUP} /opt/irisapp' 
returned a non-zero code: 1
~~~
added to fix it: 
ARG IMAGE=intersystemsdc/iris-community:2020.4.0.524.0-zpm